# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
executors:
  centos7: &centos7-executor
    docker:
      - image: tools-ext-01.ccr.xdmod.org/xdmod-10.0.0:centos7.9-0.6
  rocky8: &rocky8-executor
    docker:
      - image: tools-ext-01.ccr.xdmod.org/xdmod10.0:rockylinux8.5-0.5
jobs:
  build:
    parameters:
      os:
        type: executor
      install-type:
        type: string
    executor: << parameters.os >>
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      XDMOD_REALMS: 'jobs,storage,cloud'
      XDMOD_IS_CORE: 'yes'
      XDMOD_INSTALL_DIR: /xdmod
      XDMOD_TEST_MODE: << parameters.install-type >>
      XDMOD_SRC_DIR:  ./../xdmod
      REG_TEST_BASE: /../../../../../project/tests/artifacts/regression/current
    steps:
      - checkout
      - when:
          condition:
            equal: [ *centos7-executor, << parameters.os >> ]
          steps:
            - run:
                name: Set up environment variables for CentOS7
                command: echo "export COMPOSER=composer-el7.json" >> $BASH_ENV
      - when:
          condition:
            equal: [ *rocky8-executor, << parameters.os >> ]
          steps:
            - run:
                name: Set up environment variables for Rocky8
                command: echo "export COMPOSER=composer-el8.json" >> $BASH_ENV
            - run:
                name: Update NodeJS version
                command: |
                  dnf module -y reset nodejs
                  dnf module -y install nodejs:16
      - run:
          name: Checkout XDMoD
          command: |
            git clone --depth=1 --branch=xdmod10.5 https://github.com/ubccr/xdmod.git $XDMOD_SRC_DIR
      - run:
          name: Link the module into the XDMoD Source Directory
          command: |
              ln -s `pwd` $XDMOD_SRC_DIR/open_xdmod/modules/ondemand
      - run:
          name: Install XDMoD Dependencies
          command: composer install -d $XDMOD_SRC_DIR --no-progress
      - run:
          name: Setup Environment Variables
          command: |
            echo "export XDMOD_SOURCE_DIR=${CIRCLE_WORKING_DIRECTORY}/${XDMOD_SRC_DIR}" >> $BASH_ENV
            echo "export SHIPPABLE_BUILD_DIR=${CIRCLE_WORKING_DIRECTORY}" >> $BASH_ENV
      - run:
          name: Build RPMS
          command: |
            pushd $XDMOD_SRC_DIR
            ~/bin/buildrpm xdmod ondemand
            popd
      - run:
          name: Install / Upgrade XDMoD from RPM
          command: ./tests/scripts/bootstrap.sh
      - store_artifacts:
          path: /var/log/xdmod

workflows:
  full-build:
    jobs:
      - build:
          matrix:
            parameters:
              os: [centos7, rocky8]
              install-type: ["fresh_install", "upgrade"]
            exclude:
              - os: rocky8
                install-type: "upgrade"
